# Tomcat
server:
  port: 31001

  # Mongodb
spring:
  data:
    mongodb:
      uri: mongodb://wars:warscat@localhost:27017/admin
      database: xc_cms
  # Freemarker
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /